;; init.el

(message ":: Emacs init")
(server-start)
(add-to-list 'load-path "~/.emacs.d/conf")
(load "km-pkg.el")
(load "km-ui.el")
(load "km-general.el")
(load "km-editor.el")
(load "km-func.el")
(load "km-org.el")
(load "km-evil.el")
(load "km-ibuffer.el")
(load "km-ido.el")
(load "km-mail.el")
(load "km-python.el")
(load "km-haskell.el")
(load "km-tex.el")
(message ":: Init complete")
