(defvar init-lisp-dir (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path init-lisp-dir)

(require 'init-general)
(require 'init-pkg)
(require 'init-keymaps)

(require 'init-babel)
(require 'init-bib)
(require 'init-dired)
(require 'init-elisp)
(require 'init-func)
(require 'init-git)
(require 'init-gnus)
(require 'init-grep)
(require 'init-haskell)
(require 'init-ibuffer)
(require 'init-ido)
(require 'init-keybindings)
(require 'init-keychord)
(require 'init-modes)
(require 'init-orgcontacts)
(require 'init-org)
(require 'init-projectile)
(require 'init-python)
(require 'init-smex)
(require 'init-tex)
(require 'init-yas)
(require 'init-untracked)

(server-start)
