(require 'diminish)

(diminish 'abbrev-mode "Ab")
(after 'helm-mode (diminish 'helm-mode))
(after 'flyspell (diminish 'flyspell-mode "Fy"))
(after 'paredit (diminish 'paredit-mode " Pe"))
(after 'mml (diminish 'mml-mode "Ml"))
(after 'org (diminish 'orgstruct-mode "Os"))
(after 'org-table (diminish 'orgtbl-mode "Ot"))
(after 'projectile (diminish 'projectile-mode))
(after 'reftex (diminish 'reftex-mode "Rf"))
(after 'view (diminish 'view-mode "Vw"))
(after 'whitespace (diminish 'global-whitespace-mode))
(after 'yasnippet (diminish 'yas-minor-mode))

(provide 'init-diminish)
